version: "3.4"
services:
  hogwarts-api:
    container_name: hogwarts_api
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "postgres:postgres"
    environment:
      - host=postgres
    ports:
      - "1907:80"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
      POSGRES_DB: "hogwarts"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5439:5439"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
